#!/bin/bash

# Script Name:                    stlouis-ops-201n4 Ops Challenge:  Class 02
# Author:                         Barbara L. Beaufort
# Date of latest revision:        04/26/2023
# Purpose:                        Learning Bash Coding

# Declaration of variables
echo "I am working perfectly"
# Declaration of functions

# Main

# End
